### PR TITLE
Fix: Impossible to install package when there is no tags.

### PR DESCRIPTION
**Pull request by mikeSimonson**
The install would fail with an [ErrorException] Undefined index: name.
This was because the correct tag was return by the findPackage function
but it was not stored in the object.
I have not been able to write a test case for it so I added a todo in
the test were I think it belongs.

### CODE REVIEW

**Comment by mikeSimonson** [comment]
If you are looking for an easy test.
The package jquery-address lacks any tag.
You can test with ```bowerphp install jquery-address```

**Comment by garak** [comment]
What about setting ``protected $tag = array('name' => null);`` in line 20 instead?

**Comment by mikeSimonson** [comment]
Well that would be inconsistent to set the tag in some case in the find package method but not in others.
That doesn't mean that we shouldn't also set the tag name to null line 20.

**Comment by garak** [comment]
Where is inconsistence? The solution of predefine a null tag looks simpler to me, it's less code.

**Comment by mikeSimonson** [comment]
It's maybe not really an exact comparison but if in [line 134](https://github.com/mikeSimonson/bowerphp/blob/fix-notag/src/Bowerphp/Repository/GithubRepository.php#L134) we save the tag in the private property of the object, it seems more consistent to save it too on [line 101](https://github.com/mikeSimonson/bowerphp/blob/fix-notag/src/Bowerphp/Repository/GithubRepository.php#L101) of the same method.

**Comment by mikeSimonson** [comment]
Yeah I am really not sure about that one.

Doesn't the fact that there is no tag, means that we need to ask for master to the github api ?
Can't we consider master as a tag ?

**Comment by garak** [comment]
``null`` is fine. See the code in ``api`` method

**Comment by mikeSimonson** [comment]
I also tried to make a test that wasn't an integration one to debug that issue but I couldn't make it fail on the bug.
Maybe you have more luck than me with it.
I am not sure I get all the mocking everywhere.
https://gist.github.com/mikeSimonson/31b48758a24302852320

**Comment by garak** [comment]
Thank you Mike.
The functional test is fine (even with the possibility of a future break).
A unit test (that's harder to break) also would be great

**Comment by mikeSimonson** [comment]
Did you look at this unit test. https://gist.github.com/mikeSimonson/31b48758a24302852320

It's not working properly but it should be close.

**Pull request merged**
