### PR TITLE
getting closer to original bower by bugfixing use cases

### PR DESCRIPTION
**Pull request by surikat**
Hello again, I'm working on a large project and I have few errors with some cases which work on original bower, so I've maked adaptations (explained in commit, but ask me if isn't so clear), so if you think you can integrate them without edge effects it'll be cool

### CODE REVIEW

**Comment by garak** [comment]
You didn't run php-cs-fixer nor tests

**Comment by surikat** [comment]
Sorry I'm not very comfortable with unit tests, I've just tried to respect your coding style, and I don't understand why StyleCI add corrections to some lines that I haven't modified. I just tried to install php-cs-fixer but it seem there is a problem with the version "Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead" and exactly same message when trying to use "friendsofphp/php-cs-fixer", lol. PHPUnit return me some errors too, it seem the methods that I add to Package have to be tested and the fact that I give package object instead of package name to findPackage is affecting the unit test but it's needed to check version url, or we have to add a second parameter. I don't know what is the best option because I don't have the whole stack of bowerphp well in mind. So if you can adapt my solutions or suggest me how to do it the best way, I'll be thankful.

**Comment by garak** [comment]
I updated php-cs-fixer vendor and adjusted StyleCI settings.
Anyway, you need to fix tests if you want your PR to be merged

**Comment by surikat** [comment]
when I do
```
$ php-cs-fixer fix
```
I get
```
PHP Fatal error:  Uncaught Error: Class 'Symfony\CS\Finder\DefaultFinder' not found in /var/www/bowerphp/.php_cs:4
Stack trace:
#0 phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php(384): include()
#1 phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php(219): PhpCsFixer\Console\ConfigurationResolver->resolveConfig()
#2 phar:///usr/local/bin/php-cs-fixer/src/Console/Command/FixCommand.php(306): PhpCsFixer\Console\ConfigurationResolver->resolve()
#3 phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Command/Command.php(256): PhpCsFixer\Console\Command\FixCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Application.php(791): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Application. in /var/www/bowerphp/.php_cs on line 4
```

and when, on top of .php_cs, I add

```
require 'vendor/autoload.php';
```
 and re-trying
```
$ php-cs-fixer fix
```
I get

```
[PhpCsFixer\ConfigurationException\InvalidConfigurationException]            
  The config file: "/var/www/bowerphp/.php_cs" does not return a "PhpCsFixer\  
  ConfigInterface" instance. Got: "Symfony\CS\Config\Config".
```

**Comment by surikat** [comment]
And to fix the test, the only solution I see is to modify the test itself, should I ?

**Comment by garak** [comment]
I'm sorry but I'm force to close this PR, since it's a mess.
Please open one PR for each use case you want to fix.
In future PRs, please respect rules stated in CONTRIBUTING.md

**Comment by surikat** [comment]
OK, no problem, I was using my fork until now, but there is too many unexpected bug to fix for me now, so I moved to use composer-asset-plugin instead. But if you are really concerned by this project you should take a look to my commits and use them, maybe with a better approach and some changes, but it's up to you.

**Comment by garak** [comment]
Problem is that you failed to provide your use cases, and extracting them from code is not always an option.
For example, what's the meaning of "allow version syntax including left url"? Can you provide a real example where this happens? This is the only way a contribute can be useful.
I hope you cange your mind and try to help this project agatin.

Thanks

**Comment by surikat** [comment]
I'am sorry if it wasn't so clear, I thought that if you didn't understand by seeing the code, and message of my commit you would ask me explanations and some of my commit are very explicit (in code and messages) like: "github token support via .bowerrc", "allow token parameter", or "allow repository with no bower.json definition file to work" (it's mean even if the repository has no bower.json file, you can install it as a dependency). But I understand that my error was to make a single pull request for multiple things.

An example of "allow version syntax including left url" is in comment of the commit of "findPackage with version syntax including left url", I copy again here:
{"dependencies":{"xtabs":"https://github.com/redcatphp/xtabs.git#latest"}}
this syntax is supported by the original bower and allow to use url directly.

"version update now respect the root bower.json specifications" means that the problem was: if you specify jquery:2 in dependencies of your root bower.json file and you make "bower install any-librarary-using-jquery", the version of jquery will be replaced and don't respect anymore the required version of jquery that you put in your bower.json file at the root of the project.

I'll appreciate to help this project again but having to write unit tests (with no experience in this) and having to fight with php-cs-fixer that I didn't get to work is blocking me. But if I can bring use case and code modification suggestions to fix them, it's cool. ;)

Anyway, thank's you for this project, because I appreciate to be fully independent with PHP and all the portages of great tools that I can find on it. I'm too busy for now, but I'll return to use and help this project in future.

Friendly

**Pull request closed without merging**
